export const SEARCH_FOCUS = "header/search_focus"
export const SEARCH_BLUR = "header/search_blur"
export const GET_LIST = "header/get_list"
export const MOUSE_ENTER = "header/mouse_enter"
export const MOUSE_LEAVE = "header/mouse_leave"
export const CHANGE_PAGE = "header/change_page"